[general]
#import = [ "~/.config/alacritty/themes/themes/aura.toml" ]
import = [ "~/.config/alacritty/themes/themes/ayu_light.toml" ]

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
opacity = "0.7"

[font]
size = 14.0

[font.normal]
family = "UbuntuMonoNerdFontMono"
style = "Regular"
