#[general]
#import = [ "~/.config/alacritty/themes/themes/dawnfox.toml" ]
#import = [ "~/.config/alacritty/themes/themes/aura.toml" ]

[cursor.style]
blinking = "Always"
shape = "Block"

[env]
opacity = "0.7"

[font]
size = 16.0

[font.normal]
family="UbuntuMonoNerdFontMono" 
style = "Regular"
